# The URL the site will be built for
base_url = "https://zola-clean-blog.netlify.com"
generate_rss = true
compile_sass = true

title = "Open_SLM"
description = "An open source communication platform for spatial light modulators"
highlight_code = true

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Dave"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    # {url = "$BASE_URL/about", name = "About"},
    # {url = "$BASE_URL/contact", name = "Contact"}
]
clean_blog_social = [
    {url = "https://mp.weixin.qq.com/misc/getqrcode?fakeid=3260483065&token=1606295841", icon="fab fa-weixin"},
    {url = "https://twitter.com", icon="fab fa-twitter"},
    {url = "https://github.com/", icon="fab fa-github"},
    
#    {url = "$BASE_URL/rss.xml", icon="fas fa-rss"}
]
