# The URL the site will be built for
base_url = "https://zola-clean-blog.netlify.com"

compile_sass = true
title = "Start Bootstrap"
description = ""
highlight_code = true

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Dave"
twitter_id = "dave_tucker"
github_id = "dave-tucker"
linkedin_profile_url = ""
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"}
]
